# Form implementation generated from reading ui file 'QCheckBox复选框按钮控件.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.checkBox = QtWidgets.QCheckBox(parent=Form)
        self.checkBox.setGeometry(QtCore.QRect(90, 160, 80, 19))
        self.checkBox.setTristate(True)
        self.checkBox.setObjectName("checkBox")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(90, 120, 101, 16))
        self.label.setObjectName("label")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_2.setGeometry(QtCore.QRect(90, 190, 80, 19))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=Form)
        self.checkBox_3.setGeometry(QtCore.QRect(90, 220, 80, 19))
        self.checkBox_3.setObjectName("checkBox_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox.setText(_translate("Form", "看电影"))
        self.label.setText(_translate("Form", "您的爱好有哪些？"))
        self.checkBox_2.setText(_translate("Form", "踢足球"))
        self.checkBox_3.setText(_translate("Form", "唱歌"))
