# Form implementation generated from reading ui file 'QCommandLinkButton命令链接按钮控件.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.commandLinkButton = QtWidgets.QCommandLinkButton(parent=Form)
        self.commandLinkButton.setGeometry(QtCore.QRect(90, 110, 231, 61))
        self.commandLinkButton.setObjectName("commandLinkButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.commandLinkButton.setText(_translate("Form", "http://www.python222.com"))
        self.commandLinkButton.setDescription(_translate("Form", "python知识分享网"))
