# Form implementation generated from reading ui file 'QDoubleSpinBox小数数字选择控件.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=Form)
        self.doubleSpinBox.setGeometry(QtCore.QRect(140, 90, 81, 41))
        self.doubleSpinBox.setDecimals(3)
        self.doubleSpinBox.setMaximum(19.99)
        self.doubleSpinBox.setSingleStep(2.0)
        self.doubleSpinBox.setProperty("value", 2.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
