# Form implementation generated from reading ui file 'QSpinBox整数数字选择控件.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.spinBox = QtWidgets.QSpinBox(parent=Form)
        self.spinBox.setGeometry(QtCore.QRect(150, 90, 61, 31))
        self.spinBox.setMinimum(-1)
        self.spinBox.setMaximum(12)
        self.spinBox.setSingleStep(2)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.spinBox.setSuffix(_translate("Form", "件"))
        self.spinBox.setPrefix(_translate("Form", "第"))
