# Form implementation generated from reading ui file 'QFontComboBox字体组合框控件.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.fontComboBox = QtWidgets.QFontComboBox(parent=Form)
        self.fontComboBox.setGeometry(QtCore.QRect(130, 80, 226, 22))
        self.fontComboBox.setWritingSystem(QtGui.QFontDatabase.WritingSystem.SimplifiedChinese)
        self.fontComboBox.setFontFilters(QtWidgets.QFontComboBox.FontFilter.ScalableFonts)
        self.fontComboBox.setObjectName("fontComboBox")
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
